version: '2'
services:
   gitlab:
      image: gitlab/gitlab-ce:11.0.0-ce.0
      restart: always
      container_name: gitlab
      hostname: gitlab.sq.l
      environment:
         GITLAB_OMNIBUS_CONFIG: |
            gitlab_rails['env'] = { 'prometheus_multiproc_dir' => '/dev/shm' }
#      - TZ=${TZ}
#      - VIRTUAL_HOST=${GITLAB_HOST},${REGISTRY_HOST}
#      - VIRTUAL_PORT=80
#      - LETSENCRYPT_HOST=${GITLAB_HOST},${REGISTRY_HOST}
#      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      ports:
         - "2222:22"
         - "80:80"
         - "9418:9418"
         - "4567:4567"
         - "9090:9090"
      volumes:
         - /srv/gitlab/config:/etc/gitlab:Z
         - /srv/gitlab/logs:/var/log/gitlab:Z
         - /srv/gitlab/data:/var/opt/gitlab:Z
         - /usr/share/zoneinfo/Israel:/etc/localtime:ro

   portainer:
      image: portainer/portainer
      ports:
         - "9000:9000"
      volumes:
         - /var/run/docker.sock:/var/run/docker.sock
         - portainer_data:/data  
volumes:
   portainer_data:
